const $=id=>document.getElementById(id), history=[]; let last;
const fmtHash=v=>v==null?'—':`${Number(v).toFixed(v<100?1:0)} H/s`, fmtTime=s=>{if(s==null)return'—';const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return`${h}h ${m}m`}, fmtBytes=n=>n==null?'—':`${(n/1073741824).toFixed(1)} GB`;
function val(v,suffix=''){return v==null?'Indisponível':`${v}${suffix}`}
function render(d){last=d;const m=d.miner,s=d.system,c=d.config;$('live').textContent={running:'● Ativa',paused:'Ⅱ Pausada',stopped:'○ Parada'}[m.state];$('hashrate').textContent=fmtHash(m.hashrate.current);$('pool').textContent=c.pool;$('h1').textContent=fmtHash(m.hashrate.minute_1);$('h5').textContent=fmtHash(m.hashrate.minute_5);$('h15').textContent=fmtHash(m.hashrate.minute_15);$('uptime').textContent=fmtTime(m.uptime);$('accepted').textContent=m.shares.accepted;$('rejected').textContent=m.shares.rejected;$('reject-rate').textContent=m.shares.reject_rate+'%';$('connection').textContent=m.connection;$('wallet').textContent=c.wallet;$('cpu').textContent=val(s.cpu_percent,'%');$('temperature').textContent=val(s.temperature_c,' °C');$('frequency').textContent=val(s.frequency_mhz,' MHz');$('memory').textContent=s.memory?`${fmtBytes(s.memory.used)} / ${fmtBytes(s.memory.total)}`:'Indisponível';$('arch').textContent=`${s.architecture} · ${s.cpu_count} CPUs`;history.push(m.hashrate.current||0);if(history.length>60)history.shift();draw()}
function draw(){const cv=$('chart'),x=cv.getContext('2d'),w=cv.width,h=cv.height;x.clearRect(0,0,w,h);x.strokeStyle='#23302d';for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,i*h/5);x.lineTo(w,i*h/5);x.stroke()}const max=Math.max(...history,1);x.strokeStyle='#55e6a5';x.lineWidth=3;x.beginPath();history.forEach((v,i)=>{const px=i*w/Math.max(history.length-1,1),py=h-10-v/max*(h-20);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
new EventSource('/api/v1/events').onmessage=e=>render(JSON.parse(e.data));
function token(){let t=sessionStorage.getItem('adminToken');if(!t)$('token-dialog').showModal();return t}
$('save-token').onclick=()=>sessionStorage.setItem('adminToken',$('token').value.trim());
async function api(path){const t=token();if(!t)return;const r=await fetch(path,{method:'POST',headers:{Authorization:`Bearer ${t}`}}),j=await r.json();toast(j.error||'Comando enviado');if(r.status===401)sessionStorage.removeItem('adminToken')}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>api('/api/v1/miner/'+b.dataset.action));
$('logs').onclick=async()=>{const t=token();if(!t)return;const r=await fetch('/api/v1/logs',{headers:{Authorization:`Bearer ${t}`}}),j=await r.json();$('log-output').textContent=j.lines?.join('\n')||j.error};
function toast(v){$('toast').textContent=v;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
